title: Thi Nguyen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I deliver actionable data insights to support business decision-making through analytics.
  <br><br>
  MS in Business Analytics and Data Science at New Jersey City University 
  <br><br>
  <a href="https://www.linkedin.com/in/thi-nguyen9/">LinkedIn</a>
  <a href="https://github.com/thinguyen3">Github</a>
 
 

